import type { CatalogVariant } from './catalog.types';

/**
 * The single clean-clone demo fixture — the same eight variants db/seed/demo.sql
 * seeds into Postgres, so memory mode and a seeded database show the same shop.
 * Every other demo product array in the repo is deleted in favor of this file
 * (sidestage-code-quality-2026-08-13 P-102).
 */
export const DEMO_CATALOG_FIXTURE: readonly CatalogVariant[] = [
  {
    id: 'demo-espresso-new',
    groupId: 'demo-espresso-machine',
    title: 'Barista Pro Espresso Machine',
    brand: 'BrewHaus',
    productType: 'KITCHEN_APPLIANCE',
    sku: 'BH-ESP-200-NEW',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 49999,
    availableQty: 12,
    imageUrl: 'https://placehold.co/640x640/png?text=Barista+Pro',
    description: 'A compact dual-boiler espresso machine with a built-in grinder and steam wand.',
  },
  {
    id: 'demo-espresso-refurbished',
    groupId: 'demo-espresso-machine',
    title: 'Barista Pro Espresso Machine',
    brand: 'BrewHaus',
    productType: 'KITCHEN_APPLIANCE',
    sku: 'BH-ESP-200-REF',
    condition: 'REFURBISHED',
    handlingDays: 4,
    priceCents: 34999,
    availableQty: 4,
    imageUrl: 'https://placehold.co/640x640/png?text=Barista+Pro',
    description: 'Certified refurbished Barista Pro with the full steam wand and grinder kit.',
  },
  {
    id: 'demo-headphones-black',
    groupId: 'demo-wireless-headphones',
    title: 'Cloud ANC Wireless Headphones',
    brand: 'Northstar Audio',
    productType: 'AUDIO',
    sku: 'NSA-CLOUD-BLK',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 19999,
    availableQty: 24,
    imageUrl: 'https://placehold.co/640x640/png?text=Cloud+ANC',
    description: 'Over-ear wireless headphones with adaptive noise cancellation and a 30-hour battery.',
  },
  {
    id: 'demo-headphones-sand',
    groupId: 'demo-wireless-headphones',
    title: 'Cloud ANC Wireless Headphones',
    brand: 'Northstar Audio',
    productType: 'AUDIO',
    sku: 'NSA-CLOUD-SND',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 20999,
    availableQty: 8,
    imageUrl: 'https://placehold.co/640x640/png?text=Cloud+ANC',
    description: 'The sand colorway of the Cloud ANC, same adaptive noise cancellation.',
  },
  {
    id: 'demo-camera-body',
    groupId: 'demo-creator-camera',
    title: 'Creator 4K Mirrorless Camera',
    brand: 'FrameForge',
    productType: 'CAMERA',
    sku: 'FF-C4K-BODY',
    condition: 'NEW',
    handlingDays: 3,
    priceCents: 89999,
    availableQty: 6,
    imageUrl: 'https://placehold.co/640x640/png?text=Creator+4K',
    description: 'Lightweight mirrorless camera with 4K60 video, a flip screen, and USB-C streaming.',
  },
  {
    id: 'demo-camera-kit',
    groupId: 'demo-creator-camera',
    title: 'Creator 4K Mirrorless Camera',
    brand: 'FrameForge',
    productType: 'CAMERA',
    sku: 'FF-C4K-KIT',
    condition: 'NEW',
    handlingDays: 5,
    priceCents: 109999,
    availableQty: 3,
    imageUrl: 'https://placehold.co/640x640/png?text=Creator+4K',
    description: 'Creator 4K body with the 24-70mm kit lens and streaming rig plate.',
  },
  {
    id: 'demo-desk-bamboo',
    groupId: 'demo-standing-desk',
    title: 'Lift Electric Standing Desk',
    brand: 'Field Office',
    productType: 'OFFICE_FURNITURE',
    sku: 'FO-LIFT-BAMBOO',
    condition: 'NEW',
    handlingDays: 7,
    priceCents: 54999,
    availableQty: 10,
    imageUrl: 'https://placehold.co/640x640/png?text=Lift+Desk',
    description: 'Dual-motor electric standing desk with a bamboo top and memory presets.',
  },
  {
    id: 'demo-desk-open-box',
    groupId: 'demo-standing-desk',
    title: 'Lift Electric Standing Desk',
    brand: 'Field Office',
    productType: 'OFFICE_FURNITURE',
    sku: 'FO-LIFT-OPEN',
    condition: 'USED',
    handlingDays: 9,
    priceCents: 39999,
    availableQty: 2,
    imageUrl: 'https://placehold.co/640x640/png?text=Lift+Desk',
    description: 'Open-box Lift desk, inspected with full warranty.',
  },
];
