import type { CatalogVariant } from './catalog.types';

/**
 * The single clean-clone demo fixture — the same eight variants db/seed/demo.sql
 * seeds into Postgres, so memory mode and a seeded database show the same shop.
 * Every other demo product array in the repo is deleted in favor of this file
 * (sidestage-code-quality-2026-08-13 P-102).
 *
 * Four products, each offered in TWO COLORWAYS — colour is the axis that tells
 * one variant from its sibling here. Restart sells graded resale stock, so its
 * variants split on condition + handling days; SideStage sells live from a
 * seller's own inventory, where the buyer picks a colour. `condition` stays
 * NEW and `handlingDays` stays constant within a product group precisely so
 * neither can be mistaken for the variant axis (WI-38716).
 */
export const DEMO_CATALOG_FIXTURE: readonly CatalogVariant[] = [
  {
    id: 'demo-espresso-matte-black',
    groupId: 'demo-espresso-machine',
    title: 'Barista Pro Espresso Machine',
    brand: 'BrewHaus',
    productType: 'KITCHEN_APPLIANCE',
    sku: 'BH-ESP-200-BLK',
    color: 'Matte Black',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 49999,
    availableQty: 12,
    imageUrl: 'https://placehold.co/640x640/2f3033/ffffff/png?text=Barista+Pro+Matte+Black',
    description: 'A compact dual-boiler espresso machine with a built-in grinder and steam wand, in a matte black powder-coat.',
  },
  {
    id: 'demo-espresso-cream',
    groupId: 'demo-espresso-machine',
    title: 'Barista Pro Espresso Machine',
    brand: 'BrewHaus',
    productType: 'KITCHEN_APPLIANCE',
    sku: 'BH-ESP-200-CRM',
    color: 'Cream',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 49999,
    availableQty: 5,
    imageUrl: 'https://placehold.co/640x640/efe6d5/3a352c/png?text=Barista+Pro+Cream',
    description: 'The same dual-boiler Barista Pro in a warm cream enamel with brushed trim.',
  },
  {
    id: 'demo-headphones-midnight',
    groupId: 'demo-wireless-headphones',
    title: 'Cloud ANC Wireless Headphones',
    brand: 'Northstar Audio',
    productType: 'AUDIO',
    sku: 'NSA-CLOUD-MID',
    color: 'Midnight',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 19999,
    availableQty: 24,
    imageUrl: 'https://placehold.co/640x640/1b2033/ffffff/png?text=Cloud+ANC+Midnight',
    description: 'Over-ear wireless headphones with adaptive noise cancellation and a 30-hour battery, in midnight navy.',
  },
  {
    id: 'demo-headphones-sand',
    groupId: 'demo-wireless-headphones',
    title: 'Cloud ANC Wireless Headphones',
    brand: 'Northstar Audio',
    productType: 'AUDIO',
    sku: 'NSA-CLOUD-SND',
    color: 'Sand',
    condition: 'NEW',
    handlingDays: 2,
    priceCents: 19999,
    availableQty: 8,
    imageUrl: 'https://placehold.co/640x640/d8c6a8/3a3226/png?text=Cloud+ANC+Sand',
    description: 'The sand colorway of the Cloud ANC, same adaptive noise cancellation.',
  },
  {
    id: 'demo-camera-black',
    groupId: 'demo-creator-camera',
    title: 'Creator 4K Mirrorless Camera',
    brand: 'FrameForge',
    productType: 'CAMERA',
    sku: 'FF-C4K-BLK',
    color: 'Black',
    condition: 'NEW',
    handlingDays: 3,
    priceCents: 89999,
    availableQty: 6,
    imageUrl: 'https://placehold.co/640x640/26262a/ffffff/png?text=Creator+4K+Black',
    description: 'Lightweight mirrorless camera with 4K60 video, a flip screen, and USB-C streaming, in the classic black body.',
  },
  {
    id: 'demo-camera-silver',
    groupId: 'demo-creator-camera',
    title: 'Creator 4K Mirrorless Camera',
    brand: 'FrameForge',
    productType: 'CAMERA',
    sku: 'FF-C4K-SLV',
    color: 'Silver',
    condition: 'NEW',
    handlingDays: 3,
    priceCents: 89999,
    availableQty: 3,
    imageUrl: 'https://placehold.co/640x640/c9ccd1/2b2e33/png?text=Creator+4K+Silver',
    description: 'The Creator 4K in silver over a magnesium shell, otherwise identical to the black body.',
  },
  {
    id: 'demo-desk-natural-oak',
    groupId: 'demo-standing-desk',
    title: 'Lift Electric Standing Desk',
    brand: 'Field Office',
    productType: 'OFFICE_FURNITURE',
    sku: 'FO-LIFT-OAK',
    color: 'Natural Oak',
    condition: 'NEW',
    handlingDays: 7,
    priceCents: 54999,
    availableQty: 10,
    imageUrl: 'https://placehold.co/640x640/c8a97a/3a2c18/png?text=Lift+Desk+Natural+Oak',
    description: 'Dual-motor electric standing desk with memory presets and a natural oak top.',
  },
  {
    id: 'demo-desk-walnut',
    groupId: 'demo-standing-desk',
    title: 'Lift Electric Standing Desk',
    brand: 'Field Office',
    productType: 'OFFICE_FURNITURE',
    sku: 'FO-LIFT-WAL',
    color: 'Walnut',
    condition: 'NEW',
    handlingDays: 7,
    priceCents: 54999,
    availableQty: 2,
    imageUrl: 'https://placehold.co/640x640/5b3a2a/ffffff/png?text=Lift+Desk+Walnut',
    description: 'The same dual-motor Lift desk with a dark walnut top — the low-stock colorway.',
  },
];
